server:
  port: 8088
  servlet:
    context-path: /api/redis

spring:
  application:
    name: spring-redis
  redis:
    host: 127.0.0.1 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6389 # Redis服务器连接端口
    #    password: # Redis服务器连接密码（默认为空）
    timeout: 1000ms # 连接超时时间
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数
        max-idle: 8 # 连接池最大空闲连接数
        min-idle: 0 # 连接池最小空闲连接数
        max-wait: -1ms # 连接池最大阻塞等待时间，负值表示没有限制

eureka:
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 5 # 如果现在超过了5秒的间隔（默认是90秒）
    instance-id: redis-8088  # 在信息列表时显示主机名称
    prefer-ip-address: true     # 访问的路径变为IP地址