server:
  port: 80
spring:
  application:
    name: cloud-provider-feign-hystrix-order
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka

  instance:
    instance-id: order80
    prefer-ip-address: true
    ip-address: ${IP_ADDRESS:127.0.0.1}

feign:
  hystrix:
    enabled: true