server:
  port: 3344

spring:
  application:
    name: cloud-config-center #注册进Eureka服务器的服务名称
  cloud:
    config:
      # 下述配置生成的有效 URL 是：http://127.0.0.1:3344/main/springcloud-config.yml
      server:
        git:
#            skip-ssl-validation: true
          uri: https://github.com/paulyu12/springcloud-config/ #github仓库上面的git地址
          ##搜索目录
          search-paths: config-repo
          skip-ssl-validation: true
#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka

  instance:
    instance-id: config3344
    prefer-ip-address: true
    ip-address: ${IP_ADDRESS:127.0.0.1}