server:
  port: 8001
spring:
  application:
    name: CLOUD-PROVIDER-HYSTRIX-PAYMENT
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka

  instance:
    instance-id: payment8001
    prefer-ip-address: true
    ip-address: ${IP_ADDRESS:127.0.0.1}